

spring:
  application:
    name: authentication-aouth2
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password:
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
 
google:
  id: 660220038969-1gl4foc68ueti12oheh6tpcfshpgb70p.apps.googleusercontent.com
mySecret:
  password: 1234
server:
  port: 8081
eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka
